---
- name: Create Container
  hosts: localhost
  tasks:
    - name: Run Docker container from pulled image
      command: docker run -d --name docker_container -p 8080:8080 ajawher/git_jenkins_docker_dockerhub:v1


